first_name = input("Enter first name: ")
last_name = input("Enter last name: ")
address = input("Enter address: ")
city = input("Enter city: ")
state = input("Enter state: ")
postal_code = input("Enter postal code: ")
print("\n" + first_name + " " + last_name)
print(address)
print(city + ", " + state + " " + postal_code)
